name: GitHub Issues to Azure DevOps
  
on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@1.8
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "berbs"
          ado_project: "PartsUnlimited"
          ado_wit: "Product Backlog Item"
          ado_new_state: "New"
          ado_active_state: "Committed"
          ado_close_state: "Done"
          ado_bypassrules: true
